### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by passy** [passy/purescript-errors#10]

**Comment by passy** [comment]
Tagged, but `psc-publish` fails with

![](https://www.dropbox.com/s/qfo2jiw6gy7wxe3/Screenshot%202016-04-30%2021.30.04.png?dl=1)

I'm going to ask in IRC first because this is most likely a mistake I made somewhere in the config (paired with an unhelpful error message).

**Comment by passy** [comment]
Related issue: https://github.com/purescript/pursuit/issues/210

**Comment by passy** [comment]
Done. Thanks, @hdgarrood! :cake:

**Comment by hdgarrood** [comment]
You're welcome. :)
