### ISSUE TITLE
`note` and `hush` are available in `purescript-either`

### ISSUE THREAD

**Issue by menelaos** [passy/purescript-errors#44]
The functions `note` and `hush` have been [added]( https://github.com/purescript/purescript-either/commit/ceb6a147debe2a1b9af0732b9ee1f4a76d0c7c49) to `purescript-either` some time ago.
I thought I'd let you know in case you want to remove them from `purescript-errors`.

**Comment by paluh** [comment]
@passy - I think we should drop them as we directly depend on `purescript-either` ;-) Should I provide a PR?

@menelaos Thanks for the report!

**Comment by passy** [comment]
Thanks for reporting this! :)

@paluh - PR would be fantastic!

**Comment by paluh** [comment]
@passy Thanks for invitation!
I've created a branch with this minor change and updated suite and created a PR.

**Comment by paluh** [comment]
Merged #45
