### ISSUE TITLE
What about Data.EitherR?

### ISSUE THREAD

**Issue by paluh** [passy/purescript-errors#8]
I wonder if `Data.EitherR` is missing because there is something similar in purescript ecosystem.

Can I make one to one clone of this module and open pull request?

**Comment by passy** [comment]
@paluh No, I'm not aware of something similar in the purs ecosystem. A PR would be great! :)

**Comment by paluh** [comment]
I'm (slowly ;-)) working on it, but I'm not sure if I should port functions related to `ExceptT`: [`handleE`](https://github.com/Gabriel439/Haskell-Errors-Library/blob/master/Data/EitherR.hs#L177), [fmapLT](https://github.com/Gabriel439/Haskell-Errors-Library/blob/master/Data/EitherR.hs#L177), [flipET](https://github.com/Gabriel439/Haskell-Errors-Library/blob/master/Data/EitherR.hs#L181) as these functions are extensions to `ExcecptT` API and probably should be included in [purescript-transformers](https://github.com/purescript/purescript-transformers) package (additionally `flipET` is already implemented there - [fmapLT](https://github.com/Gabriel439/Haskell-Errors-Library/blob/master/Data/EitherR.hs#L177)).

Additionally there is [throwEither](https://github.com/Gabriel439/Haskell-Errors-Library/blob/master/Data/EitherR.hs#L107), which is nothing else but Either's [throwError](https://github.com/purescript/purescript-transformers/blob/v0.8.4/src/Control/Monad/Error/Class.purs#L47) or `Left`, but I think that it is included here for consistncy reasons (as pointed in this [comment](https://github.com/Gabriel439/Haskell-Errors-Library/blob/master/Data/EitherR.hs#L1)). I think I will clone it too.

What do you think?

**Comment by paluh** [comment]
I've forgotten to point out that `EitherR` is module which implements dual monad for `Either` and dual monad for `ExceptT` and my objections are related to this narrow specification, because above functions extend `ExceptT` API. On the other hand they (`fmapLT` and `flipET`) are clearly implemented using `ExceptRT`.

**Comment by paluh** [comment]
Ok, I've decided to clone whole module. PR is comming ;-)

**Comment by passy** [comment]
Just from quickly scanning this looks awesome. I hope I'll have some time
tonight to properly review this. Thank you! :)
